-- AlterTable
ALTER TABLE "hospitals" ADD COLUMN     "close_time" DOUBLE PRECISION NOT NULL DEFAULT 17,
ADD COLUMN     "lunch_break_end" DOUBLE PRECISION NOT NULL DEFAULT 13.5,
ADD COLUMN     "lunch_break_start" DOUBLE PRECISION NOT NULL DEFAULT 12,
ADD COLUMN     "open_time" DOUBLE PRECISION NOT NULL DEFAULT 7.5;
